
compile:
	g++ -std=c++11 analysis.cpp optimization.cpp  numeric.cpp header.h RUN.cpp network.cpp interface.cpp K_means.cpp main.cpp matrixOperation.cpp
	g++ -std=c++11 analysis.cpp optimization.cpp  numeric.cpp header.h RUN.cpp network.cpp interface.cpp K_means.cpp  main.cpp matrixOperation.cpp -o ok
